### ISSUE TITLE
pip --global-options ignored

### ISSUE THREAD

**Issue by SkyLeach** [smartfile/python-libarchive#6]
For Mac users there is a catch-22 with the default libarchive shipped with the OS.  (Tested on Sierra and El Capitain).

If one updates the core library, tons of things break in OSX.

If one doesn't update the core library, libarchive doesn't work.

missing symbol:

    Traceback (most recent call last):
      File "/Users/skyleach/.virtualenvs/imgunbundler/bin/imgunbundle", line 11, in <module>
        load_entry_point('imgunbundler', 'console_scripts', 'imgunbundle')()
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
        return ep.load()
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2287, in load
        return self.resolve()
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/Users/skyleach/src/imgunbundle/imgunbundler/imgunbundle.py", line 57, in <module>
        from unbundlers import unbundle_cpio
      File "/Users/skyleach/src/imgunbundle/imgunbundler/unbundlers/unbundle_cpio.py", line 2, in <module>
        import libarchive.public
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/libarchive/public.py", line 1, in <module>
        from libarchive.adapters.archive_read import \
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/libarchive/adapters/archive_read.py", line7, in <module>
        import libarchive.calls.archive_read
      File "/Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/libarchive/calls/archive_read.py", line 17, in <module>
        c_archive_read_support_filter_all = libarchive.archive_read_support_filter_all
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
        func = self.__getitem__(name)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x7fa97a61aca0, archive_read_support_filter_all): symbol not found

Generally the solution for mac users would be to install an updated libarchive using homebrew into `/usr/local/opt/libarchive`.

Folowing this we would instruct pip to pass the location to the module compiler using `pip install --global-option="-L/usr/local/opt/libarchive/lib" --global-option="-I/usr/local/opt/libarchive/include" libarchive`

However this doesn't work with libarchive:
```
        /Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
          cmdoptions.check_install_build_global(options)
        Collecting libarchive
          Using cached libarchive-0.4.3.tar.gz
        Requirement already satisfied: nose in /Users/skyleach/.virtualenvs/imgunbundler/lib/python2.7/site-packages (from libarchive)
        Skipping bdist_wheel for libarchive, due to binaries being disabled for it.
        Installing collected packages: libarchive
          Running setup.py install for libarchive: started
            Running setup.py install for libarchive: finished with status 'error'
            Complete output from command /Users/skyleach/.virtualenvs/imgunbundler/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-build-1krdrd/libarchive/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" -L/usr/local/opt/libarchive/lib -I/usr/local/opt/libarchive/include install --record /var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-Lpnx1J-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/skyleach/.virtualenvs/imgunbundler/bin/../include/site/python2.7/libarchive:
            usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: -c --help [cmd1 cmd2 ...]
               or: -c --help-commands
               or: -c cmd --help
            
            error: option -L not recognized
            
            ----------------------------------------
        Command "/Users/skyleach/.virtualenvs/imgunbundler/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-build-1krdrd/libarchive/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" -L/usr/local/opt/libarchive/lib -I/usr/local/opt/libarchive/include install --record /var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-Lpnx1J-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/skyleach/.virtualenvs/imgunbundler/bin/../include/site/python2.7/libarchive" failed with error code 1 in /private/var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-build-1krdrd/libarchive/
```

I grepped through the python-libarchive code for LDFLAGS and CPPFLAGS and didn't seem them being brought in.  I also tried setting them before calling pip install as environment variables: ``export LDFLAGS=' -L/usr/local/opt/libarchive/lib';export CPPFLAGS='-I/usr/local/opt/libarchive/include';export PKG_CONFIG_PATH='/usr/local/opt/libarchive/lib/pkgconfig'; pip install libarchive`` but that didn't work either.

Seems to be no way to specify which version of libarchive to link against?

**Comment by SkyLeach** [comment]
wrong libarchive, my bad
